# Generated by Django 6.0.3 on 2026-04-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.FloatField(blank=True, null=True)),
                ('interro', models.FloatField(blank=True, null=True)),
                ('examen', models.FloatField(blank=True, null=True)),
                ('note_finale', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('normal', 'Normal'), ('ABS', 'Absent')], default='normal', max_length=10)),
                ('is_submitted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
        ),
    ]
