# Generated by Django 6.0.3 on 2026-04-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_fee'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='raw_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.fee'),
            preserve_default=False,
        ),
    ]
