# Generated by Django 6.0.3 on 2026-04-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=0)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('DETTE', 'Dette')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
        ),
    ]
