# Generated by Django 6.0.3 on 2026-04-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupe',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=10, null=True),
        ),
    ]
