# Generated by Django 6.0.3 on 2026-04-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('obligatoire', models.BooleanField(default=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.promotion')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
    ]
