# Generated by Django 6.0.3 on 2026-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='genre',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
